// packages/doc-ai-angular/src/app/pages/comprehensive/comprehensive.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core'
import { NgFor, NgIf } from '@angular/common'
import { FormsModule } from '@angular/forms'
import { z } from '@opentiny/next-sdk'
import { server } from '../../../mcp-servers'
import productsData from './products.json'

// 商品类型定义
type Product = {
  id: number
  name: string
  price: number
  stock: number
  category: 'phones' | 'laptops' | 'tablets' | string
  status: 'on' | 'off' | string
  description?: string
  image?: string
}

import { ChatRemoterComponent } from '../../components/chat-remoter/chat-remoter.component'

@Component({
  selector: 'app-comprehensive',
  standalone: true,
  imports: [NgFor, NgIf, FormsModule, ChatRemoterComponent],
  templateUrl: './comprehensive.component.html',
  styleUrl: './comprehensive.component.scss'
})
export class ComprehensiveComponent implements OnInit, OnDestroy {
  products: Product[] = productsData as Product[]

  categoryLabels: Record<string, string> = {
    phones: '手机',
    laptops: '笔记本',
    tablets: '平板'
  }

  // 行内编辑状态：记录正在编辑的商品 id 和字段
  editingCell: { id: number; field: string } | null = null
  editingValue = ''

  // 用于存储 registerPageTool 返回的 cleanup 函数
  private cleanupPageTool!: () => void

  ngOnInit(): void {
    /**
     * 注册 MCP 工具：声明与执行逻辑合一
     */
    server.registerTool(
      'product-guide',
      {
        title: '产品指南',
        description: '根据产品ID获取产品详细信息',
        inputSchema: {
          productId: z.string().describe('产品ID')
        }
      },
      async ({ productId }: { productId: string }) => {
        const product = this.products.find((p) => String(p.id) === productId)
        const text = product
          ? `产品信息：${JSON.stringify(product, null, 2)}`
          : `未找到产品 ID 为 ${productId} 的商品`
        return { content: [{ type: 'text', text }] }
      }
    )
  }

  ngOnDestroy(): void {
    // 组件销毁时取消注册
    server.unregisterTool('product-guide')
  }

  // 开始行内编辑
  startEdit(id: number, field: string, value: string | number): void {
    this.editingCell = { id, field }
    this.editingValue = String(value)
  }

  // 保存行内编辑
  saveEdit(product: Product): void {
    if (!this.editingCell) return
    const { field } = this.editingCell
    if (field === 'price' || field === 'stock') {
      ;(product as Record<string, unknown>)[field] = Number(this.editingValue)
    } else {
      ;(product as Record<string, unknown>)[field] = this.editingValue
    }
    this.editingCell = null
  }

  // 取消行内编辑
  cancelEdit(): void {
    this.editingCell = null
  }

  // 判断某格是否在编辑中
  isEditing(id: number, field: string): boolean {
    return this.editingCell?.id === id && this.editingCell?.field === field
  }

  // 切换商品上架/下架状态
  toggleStatus(product: Product): void {
    product.status = product.status === 'on' ? 'off' : 'on'
  }
}

<div class="products-page">
  <div class="page-header">
    <h3>商品管理</h3>
    <div class="header-badge">实时库存监控已开启</div>
  </div>
  <div class="page-content">
    <table class="data-table">
      <thead>
        <tr>
          <th style="width: 50px">#</th>
          <th>商品信息</th>
          <th>价格</th>
          <th>库存</th>
          <th>分类</th>
          <th>状态</th>
          <th style="width: 120px">操作</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let product of products; let i = index">
          <td>{{ i + 1 }}</td>
          <td>
            <div class="product-info-cell">
              <div class="product-icon">📦</div>
              <div class="product-name-wrap">
                <ng-container *ngIf="isEditing(product.id, 'name'); else nameView">
                  <input
                    class="cell-input"
                    [(ngModel)]="editingValue"
                    (blur)="saveEdit(product)"
                    (keyup.enter)="saveEdit(product)"
                    (keyup.escape)="cancelEdit()"
                    autofocus
                  />
                </ng-container>
                <ng-template #nameView>
                  <button
                    type="button"
                    class="editable-cell"
                    (click)="startEdit(product.id, 'name', product.name)"
                  >
                    {{ product.name }}
                  </button>
                </ng-template>
                <div class="product-id">ID: {{ product.id }}</div>
              </div>
            </div>
          </td>
          <td>
            <ng-container *ngIf="isEditing(product.id, 'price'); else priceView">
              <input
                class="cell-input"
                type="number"
                [(ngModel)]="editingValue"
                (blur)="saveEdit(product)"
                (keyup.enter)="saveEdit(product)"
                (keyup.escape)="cancelEdit()"
              />
            </ng-container>
            <ng-template #priceView>
              <button
                type="button"
                class="editable-cell"
                (click)="startEdit(product.id, 'price', product.price)"
              >
                ¥{{ product.price }}
              </button>
            </ng-template>
          </td>
          <td>
            <ng-container *ngIf="isEditing(product.id, 'stock'); else stockView">
              <input
                class="cell-input"
                type="number"
                [(ngModel)]="editingValue"
                (blur)="saveEdit(product)"
                (keyup.enter)="saveEdit(product)"
                (keyup.escape)="cancelEdit()"
              />
            </ng-container>
            <ng-template #priceView>
              <button
                type="button"
                class="editable-cell"
                (click)="startEdit(product.id, 'stock', product.stock)"
              >
                {{ product.stock }}
              </button>
            </ng-template>
          </td>
          <td>{{ categoryLabels[product.category] ?? product.category }}</td>
          <td>
            <span
              class="tag"
              [class.tag-success]="product.status === 'on'"
              [class.tag-warning]="product.status !== 'on'"
            >
              {{ product.status === 'on' ? '上架' : '下架' }}
            </span>
          </td>
          <td>
            <button
              class="action-btn"
              [class.btn-danger]="product.status === 'on'"
              [class.btn-success]="product.status !== 'on'"
              (click)="toggleStatus(product)"
            >
              {{ product.status === 'on' ? '下架' : '上架' }}
            </button>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

// packages/doc-ai/src/views/comprehensive/index.vue
<template>
  <div class="products-page">
    <div class="page-header">
      <h3>商品管理</h3>
    </div>
    <div class="page-content">
      <tiny-grid
        auto-resize
        ref="gridRef"
        :data="products"
        :height="500"
        :edit-config="{ trigger: 'click', mode: 'cell', showStatus: true }"
      >
        <tiny-grid-column type="index" width="50" />
        <tiny-grid-column type="selection" width="50" />
        <tiny-grid-column field="name" title="商品名称" :editor="{ component: 'input' }" />
        <tiny-grid-column
          field="price"
          :editor="{
            component: 'input',
            attrs: { type: 'number' }
          }"
          title="价格"
        >
          <template #default="{ row }"> ¥{{ row.price }} </template>
        </tiny-grid-column>
        <tiny-grid-column
          field="stock"
          :editor="{
            component: 'input',
            attrs: { type: 'number' }
          }"
          title="库存"
        />
        <tiny-grid-column
          field="category"
          :editor="{
            component: 'select',
            options: [
              { label: '手机', value: 'phones' },
              { label: '笔记本', value: 'laptops' },
              { label: '平板', value: 'tablets' }
            ]
          }"
          title="分类"
        >
          <template #default="{ row }">
            {{ categoryLabels[row.category] }}
          </template>
        </tiny-grid-column>
        <tiny-grid-column
          field="status"
          :editor="{
            component: 'select',
            options: [
              { label: '上架', value: 'on' },
              { label: '下架', value: 'off' }
            ]
          }"
          title="状态"
        >
          <template #default="{ row }">
            <tiny-tag :type="row.status === 'on' ? 'success' : 'warning'">
              {{ row.status === 'on' ? '上架' : '下架' }}
            </tiny-tag>
          </template>
        </tiny-grid-column>
      </tiny-grid>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import { z } from '@opentiny/next-sdk'
import { server } from '../../mcp-servers'
import productsData from './products.json'

// 根据 products.json 结构定义类型，避免使用 any
type Product = {
  id: number
  name: string
  price: number
  stock: number
  category: 'phones' | 'laptops' | 'tablets' | string
  status: 'on' | 'off' | string
  description?: string
  image?: string
  createdAt?: string
  updatedAt?: string
}

const products = ref<Product[]>(productsData as Product[])

const categoryLabels: Record<string, string> = {
  phones: '手机',
  laptops: '笔记本',
  tablets: '平板'
}

const PRODUCT_GUIDE_TOOL = 'product-guide'

onMounted(() => {
  server.registerTool(
    PRODUCT_GUIDE_TOOL,
    {
      title: '产品指南',
      description: '根据产品ID获取产品详细信息',
      inputSchema: {
        productId: z.string().describe('产品ID')
      }
    },
    async ({ productId }: { productId: string }) => {
      const product = products.value.find((p) => String(p.id) === productId)
      const text = product ? `产品信息：${JSON.stringify(product, null, 2)}` : `未找到产品 ID 为 ${productId} 的商品`
      return { content: [{ type: 'text', text }] }
    }
  )
})

onUnmounted(() => {
  server.unregisterTool(PRODUCT_GUIDE_TOOL)
})
</script>

<style scoped lang="less">
.products-page {
  .page-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 15px;
    height: 32px;
  }
}

.button-box {
  display: flex;
  gap: 16px;
  margin-bottom: 20px;
  justify-content: space-between;
}
.button-box-left {
  display: flex;
  gap: 8px;
}

.loading-state {
  padding: 20px;
}

.product-image {
  width: 40px;
  height: 40px;
  border-radius: 4px;
}
.page-content {
  padding: 20px;
  background: #fff;
  border-radius: 8px;
  box-shadow: 0 2px 12px 0 rgba(0, 0, 0, 0.03);
}
</style>
