// packages/doc-ai/src/components/PriceProtectionModal.vue
<template>
  <tiny-dialog-box
    v-model:visible="visible"
    title="价保申请审核"
    width="520px"
    :modal-append-to-body="true"
    :close-on-click-modal="false"
    custom-class="pp-dialog"
  >
    <!-- AI Banner -->
    <div class="ai-banner">
      <div class="ai-avatar">
        <svg viewBox="0 0 40 40" fill="none" xmlns="http://www.w3.org/2000/svg" width="40" height="40">
          <circle cx="20" cy="20" r="20" fill="url(#grad)" />
          <!-- Brain / Circuit nodes -->
          <circle cx="20" cy="14" r="2.5" fill="white" opacity="0.9" />
          <circle cx="13" cy="23" r="2" fill="white" opacity="0.9" />
          <circle cx="27" cy="23" r="2" fill="white" opacity="0.9" />
          <circle cx="20" cy="28" r="1.8" fill="white" opacity="0.7" />
          <line x1="20" y1="16.5" x2="13.8" y2="21.2" stroke="white" stroke-width="1.2" opacity="0.6" />
          <line x1="20" y1="16.5" x2="26.2" y2="21.2" stroke="white" stroke-width="1.2" opacity="0.6" />
          <line x1="14.8" y1="24.4" x2="19" y2="27" stroke="white" stroke-width="1.2" opacity="0.6" />
          <line x1="25.2" y1="24.4" x2="21" y2="27" stroke="white" stroke-width="1.2" opacity="0.6" />
          <defs>
            <linearGradient id="grad" x1="0" y1="0" x2="40" y2="40" gradientUnits="userSpaceOnUse">
              <stop stop-color="#6366f1" />
              <stop offset="1" stop-color="#3b82f6" />
            </linearGradient>
          </defs>
        </svg>
      </div>
      <div class="ai-text">
        <div class="ai-label">AI 业务助手</div>
        <div class="ai-desc">已捕获客户价保诉求，请核实并确认以下信息后提交审批。</div>
      </div>
    </div>

    <!-- Form -->
    <tiny-form :model="formData" label-width="100px" class="pp-form">
      <tiny-form-item label="客户姓名">
        <tiny-input v-model="formData.customerName" placeholder="例如：张三" />
      </tiny-form-item>
      <tiny-form-item label="原订单号">
        <tiny-input v-model="formData.orderId" placeholder="例如：ORD-5X9A2B" />
      </tiny-form-item>
      <tiny-form-item label="补偿金额">
        <tiny-numeric
          v-model="formData.amount"
          :min="0.01"
          :max="99999"
          :precision="2"
          :step="10"
          style="width: 100%"
        />
      </tiny-form-item>
      <tiny-form-item label="申请事由">
        <tiny-input type="textarea" v-model="formData.reason" placeholder="例如：百亿补贴大促降价保底" :rows="3" />
      </tiny-form-item>
    </tiny-form>

    <template #footer>
      <div class="dialog-footer">
        <tiny-button class="btn-cancel" @click="handleCancel">驳回申请</tiny-button>
        <tiny-button class="btn-confirm" @click="handleConfirm">
          <span class="btn-icon">✓</span> 审核通过并建单
        </tiny-button>
      </div>
    </template>
  </tiny-dialog-box>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { addPriceProtectionOrder } from '../mock'

const visible = ref(false)
const formData = ref({ customerName: '', orderId: '', amount: 0, reason: '' })

let currentResolve: ((result: string) => void) | null = null

const openModal = (params: { customerName: string; orderId: string; amount: number; reason: string }) => {
  formData.value = {
    customerName: params.customerName || '',
    orderId: params.orderId || '',
    amount: params.amount || 0,
    reason: params.reason || ''
  }
  visible.value = true
  return new Promise<string>((resolve) => {
    currentResolve = resolve
  })
}

const handleConfirm = () => {
  if (!formData.value.orderId) {
    alert('原订单号不能为空')
    return
  }
  addPriceProtectionOrder({
    customerName: formData.value.customerName,
    orderId: formData.value.orderId,
    amount: formData.value.amount,
    reason: formData.value.reason
  })
  currentResolve?.(
    `价保单已建立：订单 ${formData.value.orderId}，补偿 ¥${formData.value.amount}，客户：${formData.value.customerName}。`
  )
  visible.value = false
  currentResolve = null
}

const handleCancel = () => {
  currentResolve?.('已驳回该笔价保申请。')
  visible.value = false
  currentResolve = null
}

defineExpose({ openModal })
</script>

<style>
/* 对话框外层定制 - 非 scoped 以穿透 tiny-dialog */
.pp-dialog .tiny-dialog-box__header {
  background: linear-gradient(135deg, #6366f1 0%, #3b82f6 100%);
  padding: 20px 24px 16px;
  border-radius: 12px 12px 0 0;
}
.pp-dialog .tiny-dialog-box__title {
  color: #fff !important;
  font-size: 1.05rem;
  font-weight: 600;
}
.pp-dialog .tiny-dialog-box__headerbtn .tiny-dialog-box__close {
  color: rgba(255, 255, 255, 0.8) !important;
}
.pp-dialog .tiny-dialog-box__body {
  padding: 0;
}
.pp-dialog .tiny-dialog-box__footer {
  padding: 16px 24px 20px;
  border-top: 1px solid #f0f0f0;
}
</style>

<style scoped>
/* AI Banner */
.ai-banner {
  display: flex;
  align-items: flex-start;
  gap: 14px;
  background: linear-gradient(135deg, rgba(99, 102, 241, 0.07) 0%, rgba(59, 130, 246, 0.04) 100%);
  border-left: 3px solid #6366f1;
  padding: 16px 20px;
  margin: 0 0 4px;
}
.ai-avatar {
  flex-shrink: 0;
  width: 44px;
  height: 44px;
  border-radius: 12px;
  overflow: hidden;
  box-shadow: 0 4px 14px rgba(99, 102, 241, 0.35);
}
.ai-avatar svg {
  display: block;
}
.ai-label {
  font-size: 0.8rem;
  font-weight: 700;
  color: #6366f1;
  letter-spacing: 0.03em;
  margin-bottom: 4px;
  text-transform: uppercase;
}
.ai-desc {
  font-size: 0.9rem;
  color: #374151;
  line-height: 1.5;
}

/* Form */
.pp-form {
  padding: 20px 24px 8px;
}

/* Footer */
.dialog-footer {
  display: flex;
  justify-content: flex-end;
  gap: 12px;
}

.btn-cancel {
  border: 1px solid #e5e7eb;
  color: #6b7280;
  background: #fff;
  border-radius: 8px;
  padding: 0 20px;
  font-size: 0.9rem;
  transition: all 0.2s;
}
.btn-cancel:hover {
  background: #f9fafb;
  border-color: #d1d5db;
  color: #374151;
}

.btn-confirm {
  background: linear-gradient(135deg, #6366f1 0%, #3b82f6 100%) !important;
  color: white !important;
  border: none !important;
  border-radius: 8px;
  padding: 0 24px;
  font-size: 0.9rem;
  font-weight: 600;
  box-shadow: 0 4px 14px rgba(99, 102, 241, 0.4);
  transition: all 0.2s;
  display: flex;
  align-items: center;
  gap: 6px;
}
.btn-confirm:hover {
  transform: translateY(-1px);
  box-shadow: 0 6px 18px rgba(99, 102, 241, 0.5);
}
.btn-icon {
  font-size: 1rem;
  font-weight: 700;
}
</style>

// packages/doc-ai-angular/src/app/components/price-protection-modal.component.ts
import { Component, EventEmitter, Output } from '@angular/core'
import { CommonModule } from '@angular/common'
import { FormsModule } from '@angular/forms'
import { addPriceProtectionOrder } from '../../mock'

@Component({
  selector: 'app-price-protection-modal',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="modal-overlay" *ngIf="visible" (click)="closeModal()">
      <div class="modal-content" (click)="$event.stopPropagation()">
        <div class="modal-header">
          <h3>新增价保申请</h3>
          <button class="close-btn" (click)="closeModal()">×</button>
        </div>
        <div class="modal-body">
          <form (ngSubmit)="onSubmit()" #form="ngForm">
            <div class="form-group">
              <label for="customerName">客户姓名 *</label>
              <input
                id="customerName"
                type="text"
                [(ngModel)]="formData.customerName"
                name="customerName"
                required
                placeholder="请输入客户姓名"
              />
            </div>
            <div class="form-group">
              <label for="orderId">订单号 *</label>
              <input
                id="orderId"
                type="text"
                [(ngModel)]="formData.orderId"
                name="orderId"
                required
                placeholder="请输入订单号"
              />
            </div>
            <div class="form-group">
              <label for="amount">补偿金额 *</label>
              <input
                id="amount"
                type="number"
                [(ngModel)]="formData.amount"
                name="amount"
                required
                min="0.01"
                step="0.01"
                placeholder="请输入补偿金额"
              />
            </div>
            <div class="form-group">
              <label for="reason">价保原因 *</label>
              <textarea
                id="reason"
                [(ngModel)]="formData.reason"
                name="reason"
                required
                rows="3"
                placeholder="请输入价保原因"
              ></textarea>
            </div>
            <div class="form-actions">
              <button type="button" class="btn-cancel" (click)="closeModal()">取消</button>
              <button type="submit" class="btn-submit" [disabled]="!form.valid">提交申请</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  `,
  styles: [
    `
      .modal-overlay {
        position: fixed;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background: rgba(0, 0, 0, 0.5);
        display: flex;
        align-items: center;
        justify-content: center;
        z-index: 1000;
      }

      .modal-content {
        background: white;
        border-radius: 8px;
        width: 90%;
        max-width: 500px;
        max-height: 90vh;
        overflow-y: auto;
      }

      .modal-header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding: 20px;
        border-bottom: 1px solid #e5e5e5;
      }

      .modal-header h3 {
        margin: 0;
        font-size: 18px;
        font-weight: 600;
      }

      .close-btn {
        background: none;
        border: none;
        font-size: 24px;
        cursor: pointer;
        color: #666;
        padding: 0;
        width: 30px;
        height: 30px;
        display: flex;
        align-items: center;
        justify-content: center;
      }

      .close-btn:hover {
        color: #333;
      }

      .modal-body {
        padding: 20px;
      }

      .form-group {
        margin-bottom: 16px;
      }

      .form-group label {
        display: block;
        margin-bottom: 8px;
        font-weight: 500;
        color: #333;
      }

      .form-group input,
      .form-group textarea {
        width: 100%;
        padding: 8px 12px;
        border: 1px solid #ddd;
        border-radius: 4px;
        font-size: 14px;
        font-family: inherit;
      }

      .form-group input:focus,
      .form-group textarea:focus {
        outline: none;
        border-color: #007bff;
        box-shadow: 0 0 0 2px rgba(0, 123, 255, 0.25);
      }

      .form-group textarea {
        resize: vertical;
        min-height: 60px;
      }

      .form-actions {
        display: flex;
        justify-content: flex-end;
        gap: 12px;
        margin-top: 24px;
      }

      .btn-cancel,
      .btn-submit {
        padding: 8px 16px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        font-size: 14px;
        font-weight: 500;
      }

      .btn-cancel {
        background: #f5f5f5;
        color: #666;
      }

      .btn-cancel:hover {
        background: #e5e5e5;
      }

      .btn-submit {
        background: #007bff;
        color: white;
      }

      .btn-submit:hover:not(:disabled) {
        background: #0056b3;
      }

      .btn-submit:disabled {
        background: #ccc;
        cursor: not-allowed;
      }
    `
  ]
})
export class PriceProtectionModalComponent {
  visible = false
  formData = {
    customerName: '',
    productName: '',
    unitPrice: '',
    totalAmount: '',
    orderId: '',
    amount: 0,
    reason: ''
  }

  @Output() orderAdded = new EventEmitter<any>()

  openModal(params?: { customerName: string; orderId: string; amount: number; reason: string; productName: string; unitPrice: string; totalAmount: string }): void {
    this.visible = true
    this.formData = {
      customerName: params?.customerName || '',
      orderId: params?.orderId || '',
      productName: params?.productName || '',
      unitPrice: params?.unitPrice || '',
      totalAmount: params?.totalAmount || '',
      amount: params?.amount || 0,
      reason: params?.reason || ''
    }
  }

  closeModal() {
    this.visible = false
  }

  onSubmit() {
    if (this.formData.customerName && this.formData.orderId && this.formData.amount > 0 && this.formData.reason) {
      addPriceProtectionOrder({
        customerName: this.formData.customerName,
        orderId: this.formData.orderId,
        amount: this.formData.amount,
        reason: this.formData.reason
      })
      this.orderAdded.emit(this.formData)
      this.closeModal()
    }
  }
}
